# Generated by Django 4.2.7 on 2025-10-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled'), ('ready', 'Ready'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
