# Generated by Django 4.2.7 on 2025-10-21 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_ready_at_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='display_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
